services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flixplay_app
    ports:
      - "80:4173"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
    restart: always