services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:4173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    restart: always
